import Head from 'next/head'
import Menu from '../components/Menu'
import Cover from '../components/Cover'
import About from '../components/About'
import Projects from '../components/Projects'
import CV from '../components/CV'
import ProjectModal from '../components/ProjectModal'

export default function Home() {

  return (
    <div className='w-auto overflow-x-hidden'>
      <Head>
        <title>Developer Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex'>

        {/* SideBar Menu */}
        
        <Menu />

        {/* Main Content */}

        <div className='w-screen h-screen snap-y snap-mandatory overflow-scroll scroll-smooth'>
          {/* Cover */}
          
          <Cover />

          {/* About */}

          <About />

          {/* Projects */}

          <Projects />

          {/* CV / Resume */}

          <CV />

          {/* Project Modal */}

          <ProjectModal />

        </div>
        

      </main>
    </div>
  )
}
