import Head from 'next/head'
import Menu from '../components/Menu'
import Cover from '../components/Cover'
import About from '../components/About'
import Projects from '../components/Projects'
import ProjectModal from '../components/ProjectModal'
import { useRecoilState } from 'recoil'
import { menuState } from '../atom/menuAtom'

export default function Home() {
  const [ open, setOpen ] = useRecoilState(menuState)

  return (
    <div className=''>
      <Head>
        <title>Developer Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex w-auto overflow-x-hidden'>

        {/* SideBar Menu */}
        
        <Menu />

        {/* Main Content */}
        <div onClick={() => {setOpen(false)}} className='w-screen h-screen snap-y snap-mandatory overflow-x-hidden scroll-smooth'>
          {/* Cover */}
          
          <Cover />

          {/* About */}

          <About />

          {/* Projects */}

          <Projects />

          {/* Project Modal */}

          <ProjectModal />

        </div>

        

      </main>
    </div>
  )
}
